@startuml

skinparam classAttributeIconSize 0
abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class Staff {
- staffID : int
- sName : String
- fName : String
- telNo : String
+ regStaff(): void
+ getStaffName(int): String
}

class Branch {
- bNo : int
- name : String
- telNo : String
}

class Manager {
- manID : int
- sName : String
- fName : String
}

Staff "1" -- "0.." Branch: works in >
Staff "1" -- "0.." Manager: is a >
Manager "1" -- "1..3" Branch: manages >
@enduml